### ISSUE TITLE
关于笔记应用的博文---由于站点无评论功能

### ISSUE THREAD

**Issue by lingr7** [godvmxi/godvmxi.github.io#17]
用思源笔记啊。
思源笔记现在全部开源了，唯一的缺点就是私有格式和无法使用第三方同步，比如不可以支持坚果云的webdev，只能通过文件导入导出。
不过开源了，可以自己部署后端，前端就是浏览器访问。
功能也挺丰富的。
![image](https://user-images.githubusercontent.com/37898999/185364603-7636b034-7b9d-472f-9d2d-19ae1dc485ea.png)

**Comment by godvmxi** [comment]
其实也是一个选择，但是这种自己部署后端的方式，还是门槛高了点，个人还是倾向github这种公开托管的，省事。
可以给作者提一个PR，如果能支持git 数据存储，那一定会很好玩

**Comment by godvmxi** [comment]
https://github.com/siyuan-note/siyuan/issues/6021

**Comment by lingr7** [comment]
给普通用户，提供了桌面端app。只不过是electron包的，浏览器套壳，electron首屏渲染崩溃通病，所以我就用的浏览器访问。想用不需要自己部署后端，这个软件自己就是前后端分离的网站，再包了一层桌面，所以直接启动，后台kernel进程就部署好后端了。部署后端只是siyuan提供的更多的选择。

**Comment by lingr7** [comment]
网易有道翻译也是electron做的，首屏渲染窗口经常崩溃。
electron白屏问题？ - liulun的回答 - 知乎
https://www.zhihu.com/question/54091307/answer/2322848468

**Comment by godvmxi** [comment]
> 
一般看看安装包大小就知道了，100MB左右的都是electron封装的，前端要统一世界了。。。
另外我的博客有评论功能的，disqus提供的，可能是万能的GFW给毙掉了吧。
不过这个不重要，墙国都开始玩白名单，闭关锁国指日可待，唯一跑路方可解忧。
